/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/score-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score Order */
        post: operations["score_order_api_v1_internal_score_order_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_v1_internal_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order Detail */
        get: operations["order_detail_api_v1_internal_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/orders/{order_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Override */
        post: operations["override_api_v1_internal_orders__order_id__override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/orders/{order_id}/appeal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Appeal
         * @description Placeholder lifecycle (§14.2): opens an appeal and returns its APPEAL_OPENED audit event.
         */
        post: operations["appeal_api_v1_internal_orders__order_id__appeal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Events */
        get: operations["list_audit_events_api_v1_internal_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/audit-events/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Audit Chain */
        get: operations["verify_audit_chain_api_v1_internal_audit_events_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_api_v1_internal_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["get_policy_api_v1_internal_policy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/demo/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Presets
         * @description The three §11 demo requests, as seed-db wrote them beside the database.
         */
        get: operations["presets_api_v1_internal_demo_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_api_v1_internal_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/checkout/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkout Decision */
        post: operations["checkout_decision_api_v1_public_checkout_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Action
         * @enum {string}
         */
        Action: "ALLOW" | "PREPAID_ONLY" | "MANUAL_REVIEW" | "BLOCK";
        /** ActionCost */
        ActionCost: {
            action: components["schemas"]["Action"];
            expected_cost: components["schemas"]["Money"];
            abusive_branch: components["schemas"]["Money"];
            genuine_branch: components["schemas"]["Money"];
            operational: components["schemas"]["Money"];
            /** Feasible */
            feasible: boolean;
            /** Excluded By */
            excluded_by: string[];
            /** Rank By Cost */
            rank_by_cost: number;
        };
        /** AppealRequest */
        AppealRequest: {
            /**
             * Channel
             * @enum {string}
             */
            channel: "CUSTOMER_SUPPORT" | "EMAIL";
            /** Note */
            note: string;
        };
        /** AuditEventOut */
        AuditEventOut: {
            /** Seq */
            seq: number;
            /** Event Id */
            event_id: string;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "DECISION_CREATED" | "OVERRIDE_APPLIED" | "APPEAL_OPENED";
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Order Id */
            order_id: string;
            /**
             * Actor Type
             * @enum {string}
             */
            actor_type: "SYSTEM" | "REVIEWER";
            /** Actor Id */
            actor_id: string;
            previous_action: components["schemas"]["Action"] | null;
            new_action: components["schemas"]["Action"];
            /** Policy Version */
            policy_version: string;
            /** Return Model Version */
            return_model_version: string;
            /** Abuse Model Version */
            abuse_model_version: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Prev Hash */
            prev_hash: string;
            /** Event Hash */
            event_hash: string;
        };
        /** AuditEventsResponse */
        AuditEventsResponse: {
            /** Items */
            items: components["schemas"]["AuditEventOut"][];
            /** Total */
            total: number;
        };
        /** AuditVerifyResponse */
        AuditVerifyResponse: {
            /** Valid */
            valid: boolean;
            /** Events Checked */
            events_checked: number;
            /** First Broken Seq */
            first_broken_seq: number | null;
        };
        /** BaselineOutcome */
        BaselineOutcome: {
            /**
             * Strategy
             * @enum {string}
             */
            strategy: "FIXED_THRESHOLD" | "RULE_BASED";
            action: components["schemas"]["Action"];
            /** Rule Fired */
            rule_fired: string;
        };
        /** CalibrationPoint */
        CalibrationPoint: {
            /** Bin Mean Predicted */
            bin_mean_predicted: number;
            /** Observed Rate */
            observed_rate: number;
            /** Count */
            count: number;
        };
        /** CheckoutOutcome */
        CheckoutOutcome: {
            /** Order Id */
            order_id: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "CONFIRMED" | "PREPAID_PAYMENT_REQUIRED" | "UNABLE_TO_PROCESS";
            /** Customer Message */
            customer_message: string;
            /** Support Reference */
            support_reference: string;
        };
        /**
         * CheckoutRequest
         * @description Public checkout payload. Validation is identical to ScoreOrderRequest by construction.
         */
        CheckoutRequest: {
            /** Order Id */
            order_id: string;
            /** Account Id */
            account_id: string;
            /**
             * Placed At
             * Format: date-time
             */
            placed_at: string;
            /** Lines */
            lines: components["schemas"]["OrderLineIn"][];
            /** Discount Pct */
            discount_pct: number;
            /**
             * Delivery Speed
             * @enum {string}
             */
            delivery_speed: "STANDARD" | "EXPRESS";
            /**
             * Payment Method
             * @enum {string}
             */
            payment_method: "PREPAID_CARD" | "PREPAID_UPI" | "COD";
            /** Device Id */
            device_id: string;
            /** Address Id */
            address_id: string;
            /** Payment Token Id */
            payment_token_id?: string | null;
        };
        /** CustomerSummary */
        CustomerSummary: {
            /** Account Id */
            account_id: string;
            /** Account Age Days */
            account_age_days: number;
            /** Prior Orders */
            prior_orders: number;
            /** Matured Return Rate */
            matured_return_rate: number | null;
            /** Prior Suspicious Claims 180D */
            prior_suspicious_claims_180d: number;
            clv_used_by_policy: components["schemas"]["Money"];
            /**
             * Clv Basis
             * @enum {string}
             */
            clv_basis: "HISTORY" | "NEW_CUSTOMER_FLOOR" | "CAPPED";
        };
        /** DecisionActivity */
        DecisionActivity: {
            /** Orders Evaluated */
            orders_evaluated: number;
            /** Action Distribution */
            action_distribution: {
                [key: string]: number;
            };
            /** Friction Orders */
            friction_orders: number;
            /** Manual Review Volume */
            manual_review_volume: number;
            /** Override Rate */
            override_rate: number;
            model_estimated_cost_avoided: components["schemas"]["Money"];
            /** Explanation Coverage */
            explanation_coverage: number;
            /** Version Traceability */
            version_traceability: number;
            /** Weak Evidence Decisions */
            weak_evidence_decisions: number;
        };
        /** DemoResetResponse */
        DemoResetResponse: {
            /** Status */
            status: string;
            /** Decisions */
            decisions: number;
        };
        /** DiscountedLink */
        DiscountedLink: {
            /** Identifier Label */
            identifier_label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "DEVICE" | "ADDRESS" | "PAYMENT_TOKEN";
            /**
             * Reason
             * @enum {string}
             */
            reason: "MULTI_TENANT_ADDRESS" | "SEQUENTIAL_DEVICE_USE" | "STALE_RELATIONSHIP" | "HIGH_FANOUT_IDENTIFIER" | "HOUSEHOLD_PATTERN";
            /** Weight */
            weight: number;
        };
        /** EvidenceSignal */
        EvidenceSignal: {
            /**
             * Signal
             * @enum {string}
             */
            signal: "DEVICE" | "PAYMENT_TOKEN" | "ADDRESS" | "TEMPORAL_BURST" | "ACCOUNT_CLAIMS";
            /** Present */
            present: boolean;
            /** Weight */
            weight: number;
            /** Counts For Corroboration */
            counts_for_corroboration: boolean;
            /** Detail */
            detail: string;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "USED_DEVICE" | "USED_TOKEN" | "SHIPPED_TO" | "PLACED_BY";
            /** Age Days */
            age_days: number;
            /** Reliability */
            reliability: number;
            /** Decayed Weight */
            decayed_weight: number;
            /** Counted As Evidence */
            counted_as_evidence: boolean;
            /** Discount Reason */
            discount_reason: string | null;
        };
        /** GraphEvidenceSummary */
        GraphEvidenceSummary: {
            /** Component Size Reliable 90D */
            component_size_reliable_90d: number;
            /** Confirmed Abusive Accounts In Component */
            confirmed_abusive_accounts_in_component: number;
            /** Min Hops To Confirmed Abuse */
            min_hops_to_confirmed_abuse: number | null;
            /** Linked Orders 24H */
            linked_orders_24h: number;
            /** Corroborating Signal Count */
            corroborating_signal_count: number;
            /** Signals */
            signals: components["schemas"]["EvidenceSignal"][];
            /** Discounted Links */
            discounted_links: components["schemas"]["DiscountedLink"][];
            /** Weak Evidence Only */
            weak_evidence_only: boolean;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "ACCOUNT" | "ORDER" | "DEVICE" | "ADDRESS" | "PAYMENT_TOKEN";
            /** Label */
            label: string;
            /**
             * State
             * @enum {string}
             */
            state: "CURRENT" | "CONFIRMED_ABUSE" | "LINKED" | "NEUTRAL";
            /** Flags */
            flags: ("MULTI_TENANT" | "SEQUENTIAL_DEVICE" | "HIGH_FANOUT" | "RECENT_24H")[];
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** GraphPayload */
        GraphPayload: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** Truncated */
            truncated: boolean;
            /** Hidden Node Count */
            hidden_node_count: number;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Linked Orders 24H Shown */
            linked_orders_24h_shown: number;
            /** Confirmed Peers Shown */
            confirmed_peers_shown: number;
        };
        /** GuardrailResult */
        GuardrailResult: {
            /**
             * Guardrail Id
             * @enum {string}
             */
            guardrail_id: "G1" | "G2" | "G3" | "G4" | "G5" | "G6";
            /** Name */
            name: string;
            /** Triggered */
            triggered: boolean;
            /**
             * Effect
             * @enum {string}
             */
            effect: "NONE" | "REMOVED_ACTIONS" | "FALLBACK";
            /** Removed Actions */
            removed_actions: components["schemas"]["Action"][];
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description #7: policy version, config hash prefix and the demo clock. No money, scores or thresholds.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Policy Version */
            policy_version: string;
            /** Policy Config Sha256 */
            policy_config_sha256: string;
            /** Demo Clock */
            demo_clock: string;
        };
        /** MetricsResponse */
        MetricsResponse: {
            activity: components["schemas"]["DecisionActivity"];
            /** Backtest */
            backtest: components["schemas"]["StrategyBacktest"][];
            /** Models */
            models: components["schemas"]["ModelEvaluation"][];
            /** Cold Start Ring Recall */
            cold_start_ring_recall: number;
            /** Sensitivity */
            sensitivity: {
                [key: string]: number | string;
            }[];
            /**
             * Drift Monitoring
             * @constant
             */
            drift_monitoring: "PLACEHOLDER_NOT_COMPUTED";
            /**
             * Data Notice
             * @constant
             */
            data_notice: "Synthetic data is used to validate the architecture, policy behaviour, auditability, and coordinated-pattern detection. Real deployment would require merchant-specific historical data and prospective validation.";
        };
        /** ModelEvaluation */
        ModelEvaluation: {
            /**
             * Model
             * @enum {string}
             */
            model: "RETURN" | "ABUSE";
            /** Model Version */
            model_version: string;
            /** Pr Auc */
            pr_auc: number;
            /** Pr Auc Ci95 */
            pr_auc_ci95: [
                number,
                number
            ];
            /** Brier */
            brier: number;
            /** Ece 10Bin Quantile */
            ece_10bin_quantile: number;
            /** Calibration Curve */
            calibration_curve: components["schemas"]["CalibrationPoint"][];
            /** By Value Band */
            by_value_band: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** By Cohort */
            by_cohort: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** Money */
        Money: {
            /** Inr */
            inr: number;
            /** Display */
            display: string;
        };
        /** OrderDetailResponse */
        OrderDetailResponse: {
            order: components["schemas"]["OrderSummary"];
            customer: components["schemas"]["CustomerSummary"];
            decision: components["schemas"]["ScoreOrderResponse"];
            graph: components["schemas"]["GraphPayload"];
            /** Baselines */
            baselines: components["schemas"]["BaselineOutcome"][];
            /** Audit Events */
            audit_events: components["schemas"]["AuditEventOut"][];
            current_action: components["schemas"]["Action"];
            /** Appeal Reference */
            appeal_reference: string | null;
        };
        /** OrderLineIn */
        OrderLineIn: {
            /** Sku Id */
            sku_id: string;
            /** Product Id */
            product_id: string;
            /** Variant */
            variant: string;
            /**
             * Category
             * @enum {string}
             */
            category: "APPAREL" | "FOOTWEAR" | "ELECTRONICS" | "BEAUTY" | "HOME" | "ACCESSORIES";
            /** Unit Price Inr */
            unit_price_inr: number;
            /** Quantity */
            quantity: number;
        };
        /** OrderSummary */
        OrderSummary: {
            /** Order Id */
            order_id: string;
            /**
             * Placed At
             * Format: date-time
             */
            placed_at: string;
            order_value: components["schemas"]["Money"];
            /** Discount Pct */
            discount_pct: number;
            /** Lines */
            lines: components["schemas"]["OrderLineIn"][];
            /**
             * Payment Method
             * @enum {string}
             */
            payment_method: "PREPAID_CARD" | "PREPAID_UPI" | "COD";
            /**
             * Delivery Speed
             * @enum {string}
             */
            delivery_speed: "STANDARD" | "EXPRESS";
        };
        /** OverrideRequest */
        OverrideRequest: {
            new_action: components["schemas"]["Action"];
            /**
             * Reason Category
             * @enum {string}
             */
            reason_category: "CUSTOMER_VERIFIED" | "INDEPENDENT_EVIDENCE_OF_ABUSE" | "FALSE_POSITIVE_SHARED_IDENTIFIER" | "POLICY_EXCEPTION" | "OTHER";
            /** Reason Text */
            reason_text: string;
            expected_current_action: components["schemas"]["Action"];
        };
        /** OverrideResponse */
        OverrideResponse: {
            /** Order Id */
            order_id: string;
            /** Decision Id */
            decision_id: string;
            original_recommendation: components["schemas"]["Action"];
            previous_action: components["schemas"]["Action"];
            new_action: components["schemas"]["Action"];
            /** Reviewer Id */
            reviewer_id: string;
            /**
             * Overridden At
             * Format: date-time
             */
            overridden_at: string;
            /** Audit Event Id */
            audit_event_id: string;
            /** Warnings */
            warnings: string[];
        };
        /** PolicyAssumptionSection */
        PolicyAssumptionSection: {
            /** Section */
            section: string;
            /** Values */
            values: components["schemas"]["PolicyAssumptionValue"][];
        };
        /**
         * PolicyAssumptionValue
         * @description One key of policy_v1_0.toml, exactly as the policy engine loaded it.
         */
        PolicyAssumptionValue: {
            /** Key */
            key: string;
            /** Value */
            value: number | string;
            money: components["schemas"]["Money"] | null;
        };
        /** PolicyAssumptionsResponse */
        PolicyAssumptionsResponse: {
            /** Policy Version */
            policy_version: string;
            /** Policy Config Sha256 */
            policy_config_sha256: string;
            /** Notice */
            notice: string;
            /** Sections */
            sections: components["schemas"]["PolicyAssumptionSection"][];
        };
        /** PolicyDecision */
        PolicyDecision: {
            /** Policy Version */
            policy_version: string;
            /** Policy Config Sha256 */
            policy_config_sha256: string;
            cost_optimal_action: components["schemas"]["Action"] | null;
            selected_action: components["schemas"]["Action"];
            /**
             * Selected Rule
             * @enum {string}
             */
            selected_rule: "MIN_EXPECTED_COST" | "MIN_EXPECTED_COST_WITHIN_GUARDRAILS" | "DEGRADED_MODE_FALLBACK";
            /** Costs */
            costs: components["schemas"]["ActionCost"][];
            /** Guardrails */
            guardrails: components["schemas"]["GuardrailResult"][];
            /** Policy Explanation */
            policy_explanation: string;
            /**
             * Assumptions Notice
             * @constant
             */
            assumptions_notice: "Monetary values are demonstration assumptions (policy v1.0).";
        };
        /** QueueItem */
        QueueItem: {
            /** Order Id */
            order_id: string;
            /** Decision Id */
            decision_id: string;
            /**
             * Scored At
             * Format: date-time
             */
            scored_at: string;
            order_value: components["schemas"]["Money"];
            /** P Return */
            p_return: number | null;
            /** P Abuse */
            p_abuse: number | null;
            recommended_action: components["schemas"]["Action"];
            current_action: components["schemas"]["Action"];
            /**
             * Status
             * @enum {string}
             */
            status: "AUTO_APPLIED" | "PENDING_REVIEW" | "OVERRIDDEN" | "APPEAL_OPEN";
            /** Graph Risk Summary */
            graph_risk_summary: string;
            /** Corroborating Signal Count */
            corroborating_signal_count: number;
            /**
             * Source
             * @enum {string}
             */
            source: "DEMO" | "BACKTEST_REPLAY" | "LIVE";
        };
        /** QueueResponse */
        QueueResponse: {
            /** Items */
            items: components["schemas"]["QueueItem"][];
            /** Total */
            total: number;
            /** Counts By Action */
            counts_by_action: {
                [key: string]: number;
            };
        };
        /** ReasonCode */
        ReasonCode: {
            /** Code */
            code: string;
            /**
             * Model
             * @enum {string}
             */
            model: "RETURN" | "ABUSE";
            /**
             * Direction
             * @enum {string}
             */
            direction: "INCREASES" | "DECREASES";
            /** Reviewer Text */
            reviewer_text: string;
            /** Evidence */
            evidence: {
                [key: string]: number | string;
            };
            /** Attribution Pp */
            attribution_pp: number | null;
            /**
             * Evidence Strength
             * @enum {string}
             */
            evidence_strength: "STRONG" | "MODERATE" | "WEAK";
            /** Attribution Note */
            attribution_note?: string | null;
        };
        /**
         * ScoreOrderRequest
         * @description Internal order representation at t0 = after payment-method selection, before confirmation.
         */
        ScoreOrderRequest: {
            /** Order Id */
            order_id: string;
            /** Account Id */
            account_id: string;
            /**
             * Placed At
             * Format: date-time
             */
            placed_at: string;
            /** Lines */
            lines: components["schemas"]["OrderLineIn"][];
            /** Discount Pct */
            discount_pct: number;
            /**
             * Delivery Speed
             * @enum {string}
             */
            delivery_speed: "STANDARD" | "EXPRESS";
            /**
             * Payment Method
             * @enum {string}
             */
            payment_method: "PREPAID_CARD" | "PREPAID_UPI" | "COD";
            /** Device Id */
            device_id: string;
            /** Address Id */
            address_id: string;
            /** Payment Token Id */
            payment_token_id?: string | null;
        };
        /** ScoreOrderResponse */
        ScoreOrderResponse: {
            /** Decision Id */
            decision_id: string;
            /** Order Id */
            order_id: string;
            /**
             * Scored At
             * Format: date-time
             */
            scored_at: string;
            /**
             * Features As Of
             * Format: date-time
             */
            features_as_of: string;
            scores: components["schemas"]["Scores"];
            /** Prediction Explanation */
            prediction_explanation: string;
            /** Reasons */
            reasons: components["schemas"]["ReasonCode"][];
            graph_summary: components["schemas"]["GraphEvidenceSummary"];
            policy: components["schemas"]["PolicyDecision"];
            /**
             * Status
             * @enum {string}
             */
            status: "AUTO_APPLIED" | "PENDING_REVIEW" | "OVERRIDDEN" | "APPEAL_OPEN";
            /** Audit Event Id */
            audit_event_id: string;
            /** Degraded Mode */
            degraded_mode: boolean;
            /** Idempotent Replay */
            idempotent_replay: boolean;
        };
        /** Scores */
        Scores: {
            /** P Return */
            p_return: number | null;
            /** P Abuse */
            p_abuse: number | null;
            /** P Abuse Without Graph Evidence */
            p_abuse_without_graph_evidence: number | null;
            /** Return Model Version */
            return_model_version: string;
            /** Abuse Model Version */
            abuse_model_version: string;
            /** Feature Set Version */
            feature_set_version: string;
            /**
             * P Return Used For Action
             * @default false
             * @constant
             */
            p_return_used_for_action: false;
        };
        /** StrategyBacktest */
        StrategyBacktest: {
            /**
             * Strategy
             * @enum {string}
             */
            strategy: "SENTINEL" | "FIXED_THRESHOLD" | "RULE_BASED" | "ALLOW_ALL";
            realized_cost_per_1000: components["schemas"]["Money"];
            abuse_loss_prevented: components["schemas"]["Money"];
            /** Genuine Block Rate */
            genuine_block_rate: number;
            /** Customer Friction Rate */
            customer_friction_rate: number;
            /** Manual Reviews Per 1000 */
            manual_reviews_per_1000: number;
            cost_per_detected_abuse: components["schemas"]["Money"];
            revenue_preserved: components["schemas"]["Money"];
            /** Precision Block */
            precision_block: number;
            /** Recall Intercepted */
            recall_intercepted: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    score_order_api_v1_internal_score_order_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreOrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_v1_internal_orders_get: {
        parameters: {
            query?: {
                action?: components["schemas"]["Action"] | null;
                status?: ("AUTO_APPLIED" | "PENDING_REVIEW" | "OVERRIDDEN" | "APPEAL_OPEN") | null;
                source?: ("DEMO" | "BACKTEST_REPLAY" | "LIVE") | null;
                min_p_abuse?: number | null;
                min_value_inr?: number | null;
                graph_evidence?: "ANY" | "STRONG" | "WEAK_ONLY" | "NONE";
                sort?: "scored_at_desc" | "p_abuse_desc" | "value_desc" | "exposure_desc";
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    order_detail_api_v1_internal_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-key"?: string | null;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_api_v1_internal_orders__order_id__override_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-key"?: string | null;
                "x-reviewer-id"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    appeal_api_v1_internal_orders__order_id__appeal_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-key"?: string | null;
                "x-reviewer-id"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppealRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_events_api_v1_internal_audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                order_id?: string | null;
            };
            header?: {
                "x-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_audit_chain_api_v1_internal_audit_events_verify_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_api_v1_internal_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_policy_api_v1_internal_policy_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyAssumptionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presets_api_v1_internal_demo_presets_get: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreOrderRequest"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_api_v1_internal_demo_reset_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoResetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkout_decision_api_v1_public_checkout_decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutOutcome"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
